# Generated by Django 5.1.2 on 2024-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agr_cart",
            name="products",
            field=models.ManyToManyField(
                related_name="carts",
                through="agri_cart.agr_CartItem",
                to="agri_cart.agr_product",
            ),
        ),
    ]
