# Generated by Django 5.1.2 on 2024-11-06 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_cart", "0002_alter_agr_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agr_cart",
            name="products",
        ),
        migrations.AddField(
            model_name="agr_cart",
            name="user",
            field=models.CharField(
                default="guest", max_length=100, verbose_name="用户标识"
            ),
        ),
        migrations.AlterField(
            model_name="agr_cart",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="总价"
            ),
        ),
        migrations.AlterField(
            model_name="agr_cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="agri_cart.agr_cart",
                verbose_name="购物车",
            ),
        ),
    ]
