# Generated by Django 5.1.2 on 2024-11-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_cart", "0003_remove_agr_cart_products_agr_cart_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="agr_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="guest", max_length=100)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agri_cart.agr_cart",
                    ),
                ),
            ],
        ),
    ]
