# Generated by Django 5.1.2 on 2024-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri_cart", "0004_agr_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="agr_order",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
