# Generated by Django 5.1.2 on 2024-10-29 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("deleted", "删除"),
                        ],
                        default="unread",
                        max_length=10,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "notification_type",
                    models.CharField(max_length=50, verbose_name="通知类型"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "高"), (2, "中"), (3, "低")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageModule.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统通知",
                "verbose_name_plural": "系统通知",
            },
        ),
        migrations.CreateModel(
            name="ServiceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("deleted", "删除"),
                        ],
                        default="unread",
                        max_length=10,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "service_type",
                    models.CharField(max_length=50, verbose_name="服务类型"),
                ),
                ("service_id", models.PositiveIntegerField(verbose_name="服务ID")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageModule.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务通知",
                "verbose_name_plural": "服务通知",
            },
        ),
        migrations.CreateModel(
            name="PraiseCommentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("deleted", "删除"),
                        ],
                        default="unread",
                        max_length=10,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                ("praise_or_comment", models.TextField(verbose_name="赞或评论内容")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(verbose_name="相关对象ID"),
                ),
                (
                    "related_object_type",
                    models.CharField(max_length=50, verbose_name="相关对象类型"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageModule.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "赞评消息",
                "verbose_name_plural": "赞评消息",
            },
        ),
        migrations.CreateModel(
            name="PlantingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("deleted", "删除"),
                        ],
                        default="unread",
                        max_length=10,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "plant_name",
                    models.CharField(max_length=255, verbose_name="植物名称"),
                ),
                ("plant_id", models.PositiveIntegerField(verbose_name="植物ID")),
                ("planting_date", models.DateField(verbose_name="种植日期")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageModule.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "种植消息",
                "verbose_name_plural": "种植消息",
            },
        ),
        migrations.CreateModel(
            name="WeatherReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="提醒标题")),
                ("content", models.TextField(verbose_name="提醒内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未读"),
                            ("read", "已读"),
                            ("deleted", "删除"),
                        ],
                        default="unread",
                        max_length=10,
                        verbose_name="消息状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="地点")),
                ("weather_info", models.TextField(verbose_name="天气信息")),
                ("reminder_time", models.DateTimeField(verbose_name="提醒时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messageModule.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "气象提醒",
                "verbose_name_plural": "气象提醒",
            },
        ),
    ]
