# Generated by Django 5.1.2 on 2024-11-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messageModule", "0002_messagetype_feedback_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="type_id",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="MessageType",
        ),
    ]
