# Generated by Django 5.1.2 on 2024-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HarvestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                ("address", models.TextField()),
                (
                    "crop_type",
                    models.IntegerField(
                        choices=[(1, "小麦"), (2, "玉米"), (3, "大豆"), (4, "其他")]
                    ),
                ),
            ],
            options={
                "verbose_name": "收割",
                "verbose_name_plural": "收割",
                "db_table": "harvesting",
            },
        ),
    ]
