# Generated by Django 5.1.2 on 2024-11-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0002_irrigationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvestrequest',
            old_name='crop_type',
            new_name='cropType',
        ),
    ]
