# Generated by Django 5.1.2 on 2024-11-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customized', '0003_rename_crop_type_harvestrequest_croptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plantingdate', models.DateField()),
            ],
            options={
                'verbose_name': '种植',
                'verbose_name_plural': '种植',
                'db_table': 'crop',
            },
        ),
    ]
